### ISSUE TITLE
Allow alignment to be used with node

### ISSUE THREAD

**Issue by stevenweaver** [veg/alignment.js#31]
```
15:38:44 sweaver@new-silverback gisaid-downloader master ? node translate-to-master.js /data/shares/gisaid/2020-03-29-metadata.json -o hi.json -f /data/shares/gisaid/2020-03-29.fasta 
/data/shares/veg/SARS-CoV-2/gisaid-downloader/node_modules/react-phylotree/lib/bundle.js:1
module.exports=function(t){var n={};function e(r){if(n[r])return n[r].exports;var i=n[r]={i:r,l:!1,exports:{}};return t[r].call(i.exports,i,i.exports,e),i.l=!0,i.exports}return e.m=t,e.c=n,e.d=function(t,n,r){e.o(t,n)||Object.defineProperty(t,n,{enumerable:!0,get:r})},e.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},e.t=function(t,n){if(1&n&&(t=e(t)),8&n)return t;if(4&n&&"object"==typeof t&&t&&t.__esModule)return t;var r=Object.create(null);if(e.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:t}),2&n&&"string"!=typeof t)for(var i in t)e.d(r,i,function(n){return t[n]}.bind(null,i));return r},e.n=function(t){var n=t&&t.__esModule?function(){return t.default}:function(){return t};return e.d(n,"a",n),n},e.o=function(t,n){return Object.prototype.hasOwnProperty.call(t,n)},e.p="",e(e.s=38)

ReferenceError: window is not defined
    at r (/data/shares/veg/SARS-CoV-2/gisaid-downloader/node_modules/react-phylotree/lib/bundle.js:1:182532)
    at u (/data/shares/veg/SARS-CoV-2/gisaid-downloader/node_modules/react-phylotree/lib/bundle.js:1:182620)
    at t.exports (/data/shares/veg/SARS-CoV-2/gisaid-downloader/node_modules/react-phylotree/lib/bundle.js:1:186192)
    at Object.<anonymous> (/data/shares/veg/SARS-CoV-2/gisaid-downloader/node_modules/react-phylotree/lib/bundle.js:22:77756)
    at e (/data/shares/veg/SARS-CoV-2/gisaid-downloader/node_modules/react-phylotree/lib/bundle.js:1:124)
    at Module.<anonymous> (/data/shares/veg/SARS-CoV-2/gisaid-downloader/node_modules/react-phylotree/lib/bundle.js:22:234172)
    at e (/data/shares/veg/SARS-CoV-2/gisaid-downloader/node_modules/react-phylotree/lib/bundle.js:1:124)
    at /data/shares/veg/SARS-CoV-2/gisaid-downloader/node_modules/react-phylotree/lib/bundle.js:1:923
    at Object.<anonymous> (/data/shares/veg/SARS-CoV-2/gisaid-downloader/node_modules/react-phylotree/lib/bundle.js:1:933)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
```

**Comment by stephenshank** [comment]
Dear @stevenweaver,

Thanks for the interest in the project. Here is a script I cooked up based on version 0.3.0 which uses the fasta parser (node v12.13.1). There are other utilities, like FNA parsing, and joint sorting of alignments and trees.

Did you have something more specific in mind?

### example.js
```
const fs = require('fs'),
  parser = require('alignment.js/helpers/fasta').default,
  fasta = fs.readFileSync('./example.fasta').toString(),
  parsed = parser(fasta);

console.log(parsed);
```

### Output
```
node example.js
[
  { header: 'HUMAN', seq: 'AAAGAGATTACGAATGCCAAAGAGATTACGAATGCC' },
  { header: 'CHIMP', seq: 'GAAGAGATTACGAATGCCAAAGAGATTACGAATGCC' },
  { header: 'BABOON', seq: 'AAAGAGATTAGGAATGCTAAAGAGATTACGAATGCC' },
  { header: 'COW', seq: '------------GAAAGCAAAGAGATTACGAATGCC' },
  { header: 'PIG', seq: '---------------ACTAAAGAGATTACGAATGCC' },
  { header: 'HORSE', seq: '------------AAGAATAAAGAGATTACGAATGCC' },
  { header: 'CAT', seq: '---------GCAAATGATAAAGAGATTACGAATGCC' },
  { header: 'MOUSE', seq: '---------AGAGACAATAAAGAGATTACGAATGCC' },
  { header: 'RAT', seq: '---------AGAGACAGTAAAGAGATTACGAATGC' },
  number_of_sequences: 9,
  number_of_sites: 36
]
```

### example.fasta
```
>HUMAN
AAAGAGATTACGAATGCC
AAAGAGATTACGAATGCC
>CHIMP
GAAGAGATTACGAATGCC
AAAGAGATTACGAATGCC
>BABOON
AAAGAGATTAGGAATGCT
AAAGAGATTACGAATGCC
>COW
------------GAAAGC
AAAGAGATTACGAATGCC
>PIG
---------------ACT
AAAGAGATTACGAATGCC
>HORSE
------------AAGAAT
AAAGAGATTACGAATGCC
>CAT
---------GCAAATGAT
AAAGAGATTACGAATGCC
>MOUSE
---------AGAGACAAT
AAAGAGATTACGAATGCC
>RAT
---------AGAGACAGT
```

Best,
Stephen
